### PR TITLE
Python package

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR seems big but it is mostly boilerplate to make `mocsy` an installable python module.
- All `.f90` files are inside a single private Fortran file named `_mocsy.f90`
- Added a `setup.py` that "knows" how to compile the extension.

TODO:
- [ ] Docs
- [ ] Wrap some of the Fortran calls into convenience python functions that take care of the inputs shape and size.
- [ ] Write some examples.
- [ ] Re-factor some parts of the Fortran code as pure python and/or make use of pure python module currently available (like [seawater](https://pypi.python.org/pypi/seawater)).
- [ ] Add a PyPI entry for the package since it is now pip installable too.
- [ ] Run CI tests.

ping @emiliom who requested a conda package for mocsy. (See https://github.com/ioos/conda-recipes/pull/563)

### CODE REVIEW

**Comment by jamesorr** [comment]
Thanks for this pull request.  I've just returned from travels, but will take a closer look and get back to you shortly.

**Comment by emiliom** [comment]
Thanks, Jim. I think I would suggest to hold off on accepting that pull request until we've had a chance to talk a bit more. @ocefpaf, would you agree? We've already discussed some possible changes to what's in the pull request, so I think a bit more discussion would help us get on the same page.

@jamesorr, I should emphasize that you can try our initial conda package right now. On your anaconda or miniconda installation, you just need to add the IOOS channel, then create an environment that includes the mocsy package. It could be as simple as something like this:

``` bash
# Add the IOOS channel
conda config --set show_channel_urls True
conda config --add channels ioos -f
# Create a simple conda environment with mocsy, which can run our examples notebook:
conda create -n mocsy_test python=2.7 pip ipython-notebook pandas matplotlib mocsy
```

The [examples notebook is here.](https://github.com/emiliom/mocsy/blob/python_package_em/notebooks/mocsy_examples.ipynb) This should work on Linux and OSX right now (I can vouch for Linux); Filipe may be able to say if he thinks it'll work on Windows, too.

**Comment by ocefpaf** [comment]
>  I think I would suggest to hold off on accepting that pull request until we've had a chance to talk a bit more. @ocefpaf, would you agree?

Yes.  I opened issue #2 to start the discussion.

**Comment by ocefpaf** [comment]
Note to self:  Try https://github.com/scipy/scipy/blob/81c096001974f0b5efe29ec83b54f725cc681540/scipy/fftpack/setup.py#L16-L17

**Comment by ocefpaf** [comment]
Closing this one in favor of #3

**Pull request closed without merging**
